SELECT P.PRODUCT_ID , P.PRODUCT_NAME , P.PRICE*O.TOTAL AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
JOIN 
   (SELECT O.PRODUCT_ID , sum(O.AMOUNT) as TOTAL, PRODUCE_DATE
    FROM FOOD_ORDER AS O
    WHERE DATE_FORMAT(O.PRODUCE_DATE,"%Y-%m-%d") LIKE "2022-05%"
    GROUP BY PRODUCT_ID) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY  TOTAL_SALES DESC ,  P.PRODUCT_ID